'use strict';
console.log("Running Cruise Track Test.");

// Generated by Selenium IDE
const { Builder, By, Key, until, a, WebElement, promise, Capabilities } = require('selenium-webdriver');
const fs = require('fs');

var driver;
var myArgs = process.argv.slice(2);

(async function testCruiseTrack() {

    let chromeCapabilities = Capabilities.chrome();

    // Docker will only run headless
    if ((myArgs[0] == 'headless') && (myArgs.length != 0)) {

        chromeCapabilities.set("goog:chromeOptions", {
            args: [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--headless=new",
                "--log-level=3",
                "--disable-gpu",
                "--window-size=1920,1080",
                "--force-device-scale-factor=1"
            ]
        });

    }
    else {
        chromeCapabilities.set("goog:chromeOptions", {
            args: [
                "--log-level=3",
                "--disable-gpu",
                "--window-size=1920,1080",
            ]
        });
    }

    driver = new Builder().forBrowser('chrome').withCapabilities(chromeCapabilities).build();

    try {
        if (myArgs[1] == 'public') {
            await driver.get("https://nes-lter-api.whoi.edu/cruise/ar77/track/");
        }
        else {           
            await driver.get("http://localhost:8000/cruise/ar77/track/");
        }
    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Cruise Track Test failed.");
        return 1;
    }

    // Set implict wait time in between steps
    await driver.manage().setTimeouts({ implicit: 2000 });

    try {

        // Click on Cast 1 Marker
        await driver.findElement(By.xpath("//div[@id='map']")).click();

        // Zoom out to prevent element not interactable        
        try {
            await driver.findElement(
                By.css('body > div:nth-child(2) > div:nth-child(1) > div:nth-child(4) > img:nth-child(11)')).click();
        }
        catch {
            console.log("Cruise Track Zoom.");
            await driver.findElement(By.css('.leaflet-control-zoom-out')).click();
            await new Promise(r => setTimeout(r, 2000));
            let encodedString = await driver.takeScreenshot();
            await fs.writeFileSync('screen.png', encodedString, 'base64');
            //await driver.findElement(By.xpath('//*[@id="map"]/div[1]/div[4]/img[3]')).click();
            await driver.findElement(By.xpath('//*[@id="map"]/div[1]/div[4]/img[4]')).click();  // cast 35 also on map now
        }

        await new Promise(r => setTimeout(r, 2000));
        let encodedString = await driver.takeScreenshot();
        await fs.writeFileSync('screen2.png', encodedString, 'base64');
        await driver.findElement(By.css("a[href='/cruise/ar77/cast/1/ctd_plot/']")).click();

        let handles = await driver.getAllWindowHandles();

        // Switch to the CTD Profile window
        await driver.switchTo().window(handles[1]);

        let img = await driver.findElement(By.xpath("//body//img"));
        let visible = await img.isDisplayed();

        const res = await fetch('http://localhost:8000/cruise/ar77/cast/1/ctd_plot/');
        const title = res.headers.get('x-plot-title');

        console.log("Image Title:", title);

        if (visible && title == 'ar77 Cast 1 - CTD Profile') {
            console.log("AR77 Cast 1 - CTD Profile Window Displayed.");
            console.log("Cruise Track Test Succeeded.");
        }
        else {
            console.log("AR77 Cast 1 - CTD Profile Window Not Displayed.");
            console.log("Cruise Track Test Failed.");
        }


        // Close browser window
        driver.quit();
    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Cruise Track Test failed.");
        return 1;
    }

    console.log("Cruise Track Test Completed.");
    return 0;


})();
