'use strict';
console.log("Running Landing Page Test.");

// Generated by Selenium IDE
const { Builder, By, Key, until, a, WebElement, promise, Capabilities } = require('selenium-webdriver');
const fs = require('fs');
const assert = require('assert');
const path = require("path");

var driver;
var myArgs = process.argv.slice(2);
var handles;
var files;

(async function testLandingPage() {

    let chromeCapabilities = Capabilities.chrome();

    // Docker will only run headless
    if ((myArgs[0] == 'headless') && (myArgs.length != 0)) {

        chromeCapabilities.set("goog:chromeOptions", {
            args: [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--headless=new",
                "--log-level=3",
                "--disable-gpu",
                "--window-size=1920,1080",
                "--force-device-scale-factor=1"
            ]
        });

    }
    else {
        chromeCapabilities.set("goog:chromeOptions", {
            args: [
                "--log-level=3",
                "--disable-gpu",
                "--window-size=1920,1080",
            ]
        });
    }

    driver = new Builder().forBrowser('chrome').withCapabilities(chromeCapabilities).build();

    try {
        if (myArgs[1] == 'public') {
            await driver.get("https://nes-lter-api.whoi.edu/");
        }
        else {           
            await driver.get("http://localhost:8000/");
        }
    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Landing Page Test failed.");
        return 1;
    }

    // Set implict wait time in between steps
    await driver.manage().setTimeouts({ implicit: 2000 });

    try {

        // Verify cruise years displayed for github actions
        await new Promise(r => setTimeout(r, 4000));
        var bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes("2018"));
        assert(bodyText.includes("2022"));
        assert(bodyText.includes("2023"));
        assert(bodyText.includes("2024"));

        // Verify 2023 cruise link is working
        console.log("Testing cruise and cruise detail links.");
        await driver.findElement(
            By.xpath('//div[normalize-space()="2023"]')).click();
        await new Promise(r => setTimeout(r, 4000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes("Cruises in 2023"));

        // Verify each type of cruise detail links are working
        await driver.findElement(By.css('a[href="/api/ctd/cruises/get/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[1]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('"name": "ar77"'));

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/ctd/casts/get/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[2]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('"cruise_name": "ar77", "number": "1"'));

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/ctd/bottles/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        if (process.env.GITHUB_ACTIONS === 'true') {
            var dir = "/root/Downloads";
        }
        else {
            var dir = path.join(process.env.USERPROFILE, "\\Downloads");
        }
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_ctd_bottles") && f.endsWith(".csv"))) {
            console.log("Bottles link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.findElement(By.css('a[href="/api/ctd/bottle_summary/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_ctd_bottle_summary") && f.endsWith(".csv"))) {
            console.log("Bottle Summary link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.findElement(By.css('a[href="/api/ctd/metadata/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_ctd_metadata") && f.endsWith(".csv"))) {
            console.log("Metadata link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.findElement(By.css('a[href="/api/events/get/ar77"]')).click();
        await new Promise(r => setTimeout(r, 4000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_elog") && f.endsWith(".csv"))) {
            console.log("Events link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.findElement(By.css('a[href="/api/events/instruments/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[3]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Attune Flow Cytometer'));

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/events/history/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[4]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes(''));

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/underway/get/ar77"]')).click();
        await new Promise(r => setTimeout(r, 4000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_underway") && f.endsWith(".csv"))) {
            console.log("Underway Data link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.findElement(By.css('a[href="/api/underway/get_column_headers/ar77"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[5]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('"date", "dec_lat"'));

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/hplc/ar77"]')).click();
        await new Promise(r => setTimeout(r, 4000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_hplc") && f.endsWith(".csv"))) {
            console.log("HPLC Data link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/nut/ar77"]')).click();
        await new Promise(r => setTimeout(r, 4000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_nut") && f.endsWith(".csv"))) {
            console.log("Nutrient Data link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/api/chl/ar77"]')).click();
        await new Promise(r => setTimeout(r, 4000));
        files = fs.readdirSync(dir);
        if (!files.some(f => f.includes("ar77_chl") && f.endsWith(".csv"))) {
            console.log("Chlorophyll Data link broken.");
            console.log("Land Page Test Failed.");
        }

        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.xpath("//div[contains(@onclick, \"cruise_name=ar77\")]")).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[6]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('READMEs for Cruise AR77'));

        // Verify all Back To links are working
        console.log("Testing Back To links.");
        await driver.switchTo().window(handles[0]);
        await driver.findElement(By.css('a[href="/cruises/type/"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Cruises by Ship'));

        await driver.findElement(By.xpath('//div[normalize-space()="AR Cruises"]')).click();
        await driver.findElement(By.css('a[href="/cruises/year/"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Cruises by Year'));

        await driver.findElement(By.xpath('//div[normalize-space()="2023"]')).click();
        await driver.findElement(By.css('a[href="/cruises/season/"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Cruises by Season'));

        await driver.findElement(By.xpath('//div[normalize-space()="Fall"]')).click();
        await driver.findElement(By.css('a[href="/"]')).click();
        await new Promise(r => setTimeout(r, 2000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('NES-LTER API 2'));

        // Test the remaining links on the landing page
        console.log("Testing remaining landing page links.");
        var dropdown = await driver.findElement(By.id("cruise-nav"));
        await dropdown.findElement(By.xpath("//option[. = 'by Ship']")).click();
        await new Promise(r => setTimeout(r, 2000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Cruises by Ship'));

        await driver.navigate().back();
        await new Promise(r => setTimeout(r, 2000));
        dropdown = await driver.findElement(By.id("cruise-nav"));
        await dropdown.findElement(By.xpath("//option[. = 'by Season']")).click();
        await new Promise(r => setTimeout(r, 2000));
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Cruises by Season'));

        await driver.navigate().back()
        await driver.findElement(By.linkText('NES-LTER API 2 Wiki')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[7]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('REST API'));

        await driver.switchTo().window(handles[0]);
        await new Promise(r => setTimeout(r, 2000));
        await driver.findElement(By.linkText('Interactive Docs')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[8]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('Access cruise, CTD, and underway datasets for NES-LTER.'));

        await driver.switchTo().window(handles[0]);
        await new Promise(r => setTimeout(r, 2000));
        await driver.findElement(By.linkText('Colab Notebook')).click();
        await new Promise(r => setTimeout(r, 2000));
        handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[9]);
        bodyText = await driver.findElement(By.css("body")).getText();
        assert(bodyText.includes('The NES-LTER API is designed to provide data'));




        // Close browser window
        driver.quit();
    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Landing Page Test failed.");
        return 1;
    }

    console.log("Landing Page Test Succeeded.");
    return 0;


})();
