'use strict';
console.log("Running Upload Test.");

// Generated by Selenium IDE
const { Builder, By, Key, until, a, WebElement, promise, Capabilities } = require('selenium-webdriver');

var driver;
var filename;
var bodyText;
var file1, file2, file3, file4, file5, file6
var myArgs = process.argv.slice(1);

(async function upload() {

    let chromeCapabilities = Capabilities.chrome();

    // Docker will only run headless
    if ((myArgs[1] == 'headless') && (myArgs.length != 0)) {

        chromeCapabilities.set("goog:chromeOptions", {
            args: [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--headless",
                "--log-level=3",
                "--disable-gpu"
            ]
        });

    }
    else {
        chromeCapabilities.set("goog:chromeOptions", {
            args: [
                "--log-level=3",
                "--disable-gpu"
            ]
        });
    }

    driver = new Builder().forBrowser('chrome').withCapabilities(chromeCapabilities).build();

    try {
        if (myArgs[2] == 'public') {
            await driver.get("https://mullen.whoi.edu/upload/");
        }
        else {           
            await driver.get("http://localhost:8000/upload");
        }
    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Upload failed.");
        return 1;
    }

    await driver.manage().window().setRect({ width: 1304, height: 1234 });
    // Set implict wait time in between steps
    await driver.manage().setTimeouts({ implicit: 2000 });


    try {

        // login
        await driver.findElement(By.id("id_username")).sendKeys("admin");
        await driver.findElement(By.id("id_password")).sendKeys("admin");
        await driver.findElement(By.css(".login-button")).click();

        // Upload CTD file
        console.log("Upload CTD file.");
        await driver.findElement(By.id("cruise-name")).sendKeys("ar77");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//ar77_001.hdr";
        }
        else {
            filename = process.cwd() + "\\ar77_001.hdr";
        }
        let fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        let alert = await driver.switchTo().alert();
        await alert.accept();  

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 10; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("Import completed successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        // Upload Elog file
        console.log("Upload Elog file.");
        await driver.findElement(By.id("file-type")).sendKeys("Elog");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//R2R_ELOG_ar77_FINAL_EVENTLOG_20231016_162511.csv";
        }
        else {
            filename = process.cwd() + "\\R2R_ELOG_ar77_FINAL_EVENTLOG_20231016_162511.csv";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        alert = await driver.switchTo().alert();
        await alert.accept();

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 10; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("Import completed successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        // Upload Underway files
        console.log("Upload Underway files.");
        await driver.findElement(By.id("file-type")).sendKeys("Underway"); 
        if (myArgs[1] == 'headless') {
            file1 = process.cwd() + "//AR231011_0000.csv";
            file2 = process.cwd() + "//AR231015_0000.csv";
            file3 = process.cwd() + "//AR231014_0000.csv";
            file4 = process.cwd() + "//AR231013_0000.csv";
            file5 = process.cwd() + "//AR231012_0000.csv";
            file6 = process.cwd() + "//AR231011_0000.csv";
        }
        else {
            file1 = process.cwd() + "\\AR231011_0000.csv";
            file2 = process.cwd() + "\\AR231015_0000.csv";
            file3 = process.cwd() + "\\AR231014_0000.csv";
            file4 = process.cwd() + "\\AR231013_0000.csv";
            file5 = process.cwd() + "\\AR231012_0000.csv";
            file6 = process.cwd() + "\\AR231011_0000.csv";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        //await fileInput.sendKeys(filename);
        await fileInput.sendKeys(`${file1}\n${file2}\n${file3}\n${file4}\n${file5}\n${file6}`);

        // read and accept file exists alert for the 6 files
        for (var j = 0; j < 6; j++) {
            await driver.wait(until.alertIsPresent(), 5000);
            alert = await driver.switchTo().alert();
            await alert.accept();
        }
        
        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 15; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("File overwritten successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        await new Promise(r => setTimeout(r, 2000));

        // Upload LTERnut file
        console.log("Upload LTERnut file.");
        await driver.findElement(By.id("file-type")).sendKeys("LTERnut.xlsx");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//LTERnut.xlsx";
        }
        else {
            filename = process.cwd() + "\\LTERnut.xlsx";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        alert = await driver.switchTo().alert();
        await alert.accept();

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 15; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("File overwritten successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        await new Promise(r => setTimeout(r, 2000));

        // Upload Sample Log file
        console.log("Upload Sample Log file.");
        await driver.findElement(By.id("file-type")).sendKeys("LTER_sample_log.xlsx");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//LTER_sample_log.xlsx";
        }
        else {
            filename = process.cwd() + "\\LTER_sample_log.xlsx";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        alert = await driver.switchTo().alert();
        await alert.accept();

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 15; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("File overwritten successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        await new Promise(r => setTimeout(r, 2000));

        // Upload Station List file
        console.log("Upload Station List file.");
        await driver.findElement(By.id("file-type")).sendKeys("NES-LTER_station_list_compilation.xlsx");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//NES-LTER_station_list_compilation.xlsx";
        }
        else {
            filename = process.cwd() + "\\NES-LTER_station_list_compilation.xlsx";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        alert = await driver.switchTo().alert();
        await alert.accept();

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 15; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("Import completed successfully.")) {
                 console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        await new Promise(r => setTimeout(r, 2000));

        // Upload Sosik Report file
        console.log("Upload Sosik Report file.");
        await driver.findElement(By.id("file-type")).sendKeys("Sosik*report.xlsx");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//Sosik_13-07_report.xlsx";
        }
        else {
            filename = process.cwd() + "\\Sosik_13-07_report.xlsx";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        alert = await driver.switchTo().alert();
        await alert.accept();

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 15; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("File overwritten successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        await new Promise(r => setTimeout(r, 2000));

        // Upload Chlorophyll file
        console.log("Upload Chlorophyll file.");
        await driver.findElement(By.id("file-type")).sendKeys("NESLTERchl.xlsx");
        if (myArgs[1] == 'headless') {
            filename = process.cwd() + "//NESLTERchl.xlsx";
        }
        else {
            filename = process.cwd() + "\\NESLTERchl.xlsx";
        }
        fileInput = await driver.wait(
            until.elementLocated(By.css('#myDropzone input[type="file"], .dz-hidden-input')),
            10_000
        );
        await fileInput.sendKeys(filename);

        await driver.wait(until.alertIsPresent(), 5000);

        // read and accept file overwrite
        alert = await driver.switchTo().alert();
        await alert.accept();

        bodyText = await driver.findElement(By.css('body')).getText();
        if (bodyText.includes("Please wait... Uploading and processing your file.")) {
            console.log("Please wait... Uploading and processing your file.");
        }
        //Import completed successfully.
        for (var j = 0; j < 15; j++) {
            bodyText = await driver.findElement(By.css('body')).getText();
            if (bodyText.includes("File overwritten successfully.")) {
                console.log("Import completed successfully.");
                break;
            }
            else {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        console.log("Upload test successful.");

        // Close browser window
        driver.quit();
    }
    catch (e) {
        console.log(e.message, e.stack);
        console.log("Upload Test failed.");
        return 1;
    }

    console.log("Upload Test completed.");
    return 0;


})();
