# Generated by Django 5.1 on 2024-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cruise_cast_niskin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='designation',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='cast',
            constraint=models.UniqueConstraint(fields=('cruise', 'number'), name='unique_cruise_cast_number'),
        ),
        migrations.AddConstraint(
            model_name='niskin',
            constraint=models.UniqueConstraint(fields=('cast', 'number'), name='unique_cast_niskin_number'),
        ),
    ]
