# Generated by Django 5.1 on 2024-08-21 14:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vessel_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('instrument', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=200)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('datetime', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cruise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.cruise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('instrument', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=200)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('datetime', models.DateTimeField()),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.cruise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cruise', 'number'), name='unique_cruise_event_number')],
            },
        ),
    ]
