# Generated by Django 5.1.4 on 2024-12-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Underway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underway', to='core.cruise')),
            ],
        ),
    ]
