# Generated by Django 5.1.5 on 2025-01-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_underway'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_cruise_event_number',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='number',
            new_name='message_id',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='number',
            new_name='message_id',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('cruise', 'message_id'), name='unique_cruise_message_id'),
        ),
    ]
