# Generated by Django 5.1.5 on 2025-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_event_unique_cruise_event_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underway',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='underway',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='underway',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='underway',
            name='start_year',
        ),
        migrations.AddField(
            model_name='underway',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='underway',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
