# Generated by Django 5.1.6 on 2025-02-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_underway_end_month_remove_underway_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
