# Generated by Django 5.2 on 2025-04-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_event_comment_alter_historicalevent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cruise',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
