# Generated by Django 5.2.3 on 2025-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hplc_alter_cruise_start_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_cruise_message_id',
        ),
        migrations.AddField(
            model_name='event',
            name='r2r_event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='r2r_event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('cruise', 'r2r_event'), name='unique_cruise_r2r_event'),
        ),
    ]
