# Generated by Django 6.0.5 on 2026-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_event_unique_cruise_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='type',
            field=models.CharField(choices=[('NESLTER', 'Neslter'), ('JP Student', 'Jp Student'), ('MAB Pioneer', 'MAB Pioneer')], default='NESLTER', max_length=32),
        ),
    ]
