# Generated by Django 6.0.5 on 2026-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cruise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='type',
            field=models.CharField(choices=[('NESLTER', 'Neslter'), ('JP Student', 'Jp Student'), ('OOI Pioneer', 'Ooi Pioneer'), ('Opportunistic', 'Opportunistic')], default='NESLTER', max_length=32),
        ),
    ]
