# Generated by Django 6.0.5 on 2026-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cruise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='type',
            field=models.CharField(choices=[('NESLTER', 'Neslter'), ('JP Student', 'Jp Student'), ('OOI NES', 'Ooi Nes'), ('OOI MAB', 'Ooi Mab'), ('Opportunistic', 'Opportunistic')], default='NESLTER', max_length=32),
        ),
    ]
