# Generated by Django 6.0.6 on 2026-06-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cruise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='type',
            field=models.CharField(choices=[('NES-LTER', 'Neslter'), ('JP Student', 'Jp Student'), ('OOI-NES', 'Ooi Nes'), ('OOI-MAB', 'Ooi Mab'), ('Opportunistic', 'Opportunistic')], default='NES-LTER', max_length=32),
        ),
    ]
